When say is 'source'd, define 'say' as a function for use in the calling script

diff --git a/say b/say
--- a/say
+++ b/say
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 read -r -d '' VERSION <<'HERE'
-say version 1.0
+say version 1.1
 Copyright (c) 2020 Jeff Ober
 License MIT: https://mit-license.org/
 
@@ -78,113 +78,142 @@ HERE
 
 
 #-------------------------------------------------------------------------------
-# Scan for arguments to say
+# Determine if the script is being loaded as a library (via the 'source'
+# command) or directly.
 #-------------------------------------------------------------------------------
-NEWLINE=1
-ESCAPES=0
-ECHO_ARGS="-n"
+AS_LIB=0
 
-for arg in "$@"; do
-    case $arg in
-        --help|-h)
-            echo "$USAGE"
-            echo
-            exit 0
-            ;;
+# Try to execute a `return` statement, but do it in a sub-shell and catch the
+# results. If this script isn't sourced, that will raise an error.
+$(return >/dev/null 2>&1)
 
-        --version|-v)
-            echo "$VERSION"
-            echo
-            exit 0
-            ;;
-
-        -n)
-            NEWLINE=0
-            shift
-            ;;
-
-        -e)
-            ESCAPES=1
-            shift
-            ;;
-
-        -E)
-            ESCAPES=0
-            shift
-            ;;
-
-        *)
-            break;
-            ;;
-    esac
-done
-
-if [ $ESCAPES -eq 1 ];
-    then ECHO_ARGS+=" -e";
+# What exit code did that give?
+if [ "$?" -eq "0" ]; then
+    AS_LIB=1
 fi
 
-
 #-------------------------------------------------------------------------------
-# Process each token in the list
+# Set defaults for control variables
 #-------------------------------------------------------------------------------
-for tok in "$@"; do
-    case $tok in
-        Clear)           echo -n -e "\e[0m";;
-        Reset)           echo -n -e "\e[0m";;
-        Bold)            echo -n -e "\e[1m";;
-        Dim)             echo -n -e "\e[2m";;
-        Italic)          echo -n -e "\e[3m";;
-        Underline)       echo -n -e "\e[4m";;
-        Blink)           echo -n -e "\e[5m";;
-        Invert)          echo -n -e "\e[7m";;
-        Hidden)          echo -n -e "\e[8m";;
-        Default)         echo -n -e "\e[39m";;
+: ${SAY_NEWLINE:=1}
+: ${SAY_ESCAPES:=0}
+ECHO_ARGS='-n'
 
-        Black)           echo -n -e "\e[30m";;
-        Blue)            echo -n -e "\e[34m";;
-        Cyan)            echo -n -e "\e[36m";;
-        Green)           echo -n -e "\e[32m";;
-        Magenta)         echo -n -e "\e[35m";;
-        Red)             echo -n -e "\e[31m";;
-        White)           echo -n -e "\e[37m";;
-        Yellow)          echo -n -e "\e[33m";;
+function say:main {
+    #---------------------------------------------------------------------------
+    # Scan for arguments to say
+    #---------------------------------------------------------------------------
+    for arg in "$@"; do
+        case $arg in
+            --help|-h)
+                echo "$USAGE"
+                echo
+                exit 0
+                ;;
 
-        Bold_Black)      echo -n -e "\e[90m";;
-        Bold_Blue)       echo -n -e "\e[94m";;
-        Bold_Cyan)       echo -n -e "\e[96m";;
-        Bold_Green)      echo -n -e "\e[92m";;
-        Bold_Magenta)    echo -n -e "\e[95m";;
-        Bold_Red)        echo -n -e "\e[91m";;
-        Bold_White)      echo -n -e "\e[97m";;
-        Bold_Yellow)     echo -n -e "\e[93m";;
+            --version|-v)
+                echo "$VERSION"
+                echo
+                exit 0
+                ;;
 
-        On_Black)        echo -n -e "\e[40m";;
-        On_Blue)         echo -n -e "\e[44m";;
-        On_Cyan)         echo -n -e "\e[46m";;
-        On_Green)        echo -n -e "\e[42m";;
-        On_Magenta)      echo -n -e "\e[45m";;
-        On_Red)          echo -n -e "\e[41m";;
-        On_White)        echo -n -e "\e[47m";;
-        On_Yellow)       echo -n -e "\e[43m";;
+            -n)
+                SAY_NEWLINE=0
+                shift
+                ;;
 
-        On_Bold_Black)   echo -n -e "\e[100m";;
-        On_Bold_Blue)    echo -n -e "\e[104m";;
-        On_Bold_Cyan)    echo -n -e "\e[106m";;
-        On_Bold_Green)   echo -n -e "\e[102m";;
-        On_Bold_Magenta) echo -n -e "\e[105m";;
-        On_Bold_Red)     echo -n -e "\e[101m";;
-        On_Bold_White)   echo -n -e "\e[107m";;
-        On_Bold_Yellow)  echo -n -e "\e[103m";;
+            -e)
+                SAY_ESCAPES=1
+                shift
+                ;;
 
-        Ansi_*)          echo -n -e "\e[38;5;${tok/Ansi_/}m";;
-        On_Ansi_*)       echo -n -e "\e[48;5;${tok/On_Ansi_/}m";;
+            -E)
+                SAY_ESCAPES=0
+                shift
+                ;;
 
-        *)               echo $ECHO_ARGS "$tok";;
-    esac
-done
+            *)
+                break;
+                ;;
+        esac
+    done
 
-echo -e -n "\e[0m"
+    if [ $SAY_ESCAPES -eq 1 ];
+        then ECHO_ARGS+=" -e";
+    fi
 
-if [ $NEWLINE -eq 1 ]; then
-    echo
+    #---------------------------------------------------------------------------
+    # Process each token in the list
+    #---------------------------------------------------------------------------
+    for tok in "$@"; do
+        case $tok in
+            Clear)           echo -n -e "\e[0m";;
+            Reset)           echo -n -e "\e[0m";;
+            Bold)            echo -n -e "\e[1m";;
+            Dim)             echo -n -e "\e[2m";;
+            Italic)          echo -n -e "\e[3m";;
+            Underline)       echo -n -e "\e[4m";;
+            Blink)           echo -n -e "\e[5m";;
+            Invert)          echo -n -e "\e[7m";;
+            Hidden)          echo -n -e "\e[8m";;
+            Default)         echo -n -e "\e[39m";;
+
+            Black)           echo -n -e "\e[30m";;
+            Blue)            echo -n -e "\e[34m";;
+            Cyan)            echo -n -e "\e[36m";;
+            Green)           echo -n -e "\e[32m";;
+            Magenta)         echo -n -e "\e[35m";;
+            Red)             echo -n -e "\e[31m";;
+            White)           echo -n -e "\e[37m";;
+            Yellow)          echo -n -e "\e[33m";;
+
+            Bold_Black)      echo -n -e "\e[90m";;
+            Bold_Blue)       echo -n -e "\e[94m";;
+            Bold_Cyan)       echo -n -e "\e[96m";;
+            Bold_Green)      echo -n -e "\e[92m";;
+            Bold_Magenta)    echo -n -e "\e[95m";;
+            Bold_Red)        echo -n -e "\e[91m";;
+            Bold_White)      echo -n -e "\e[97m";;
+            Bold_Yellow)     echo -n -e "\e[93m";;
+
+            On_Black)        echo -n -e "\e[40m";;
+            On_Blue)         echo -n -e "\e[44m";;
+            On_Cyan)         echo -n -e "\e[46m";;
+            On_Green)        echo -n -e "\e[42m";;
+            On_Magenta)      echo -n -e "\e[45m";;
+            On_Red)          echo -n -e "\e[41m";;
+            On_White)        echo -n -e "\e[47m";;
+            On_Yellow)       echo -n -e "\e[43m";;
+
+            On_Bold_Black)   echo -n -e "\e[100m";;
+            On_Bold_Blue)    echo -n -e "\e[104m";;
+            On_Bold_Cyan)    echo -n -e "\e[106m";;
+            On_Bold_Green)   echo -n -e "\e[102m";;
+            On_Bold_Magenta) echo -n -e "\e[105m";;
+            On_Bold_Red)     echo -n -e "\e[101m";;
+            On_Bold_White)   echo -n -e "\e[107m";;
+            On_Bold_Yellow)  echo -n -e "\e[103m";;
+
+            Ansi_*)          echo -n -e "\e[38;5;${tok/Ansi_/}m";;
+            On_Ansi_*)       echo -n -e "\e[48;5;${tok/On_Ansi_/}m";;
+
+            *)               echo $ECHO_ARGS "$tok";;
+        esac
+    done
+
+    echo -e -n "\e[0m"
+
+    if [ $SAY_NEWLINE -eq 1 ]; then
+        echo
+    fi
+}
+
+# If being sourced as a library, then define 'say' as a function. Otherwise,
+# run say:main directly.
+if [ $AS_LIB -eq 1 ]; then
+    function say {
+        say:main $@
+    }
+else
+    say:main $@
 fi
